spring:
  application:
    name: ex-radar
  jpa:
    open-in-view: false
  flyway:
    enabled: true
  thymeleaf:
    cache: true
  profiles:
    default: dev
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
exradar:
  analytics:
    measurement-id: ${GA4_MEASUREMENT_ID:}
