-- 体験談詳細ページを最後まで読んだ場合にのみ記録する既読情報。
-- created_at=初回既読日時、updated_at=最終既読日時として扱う(BaseEntityの標準カラムを流用)。
-- (user_id, post_id)にUNIQUE制約を設け、同一体験談の再読で行が重複しないようにする。
-- 将来の「未読のみ表示」「最近読んだ体験談」「おすすめ」機能もこのテーブルのみで実現できる。
CREATE TABLE experience_reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(post_id) REFERENCES experience_posts(id),
  CONSTRAINT uk_experience_read_user_post UNIQUE(user_id, post_id)
);
CREATE INDEX idx_experience_reads_user ON experience_reads(user_id);
