-- 運営から会員への一括/個別メッセージ配信。メッセージ本体と受信者・既読状態を分離する。
-- created_by_admin_idはNULL許容: 送信した管理者アカウントが退会した場合でも
-- メッセージ本体・他の受信者のレコードは残す(created_by_admin_idだけNULLにする)ため。
CREATE TABLE admin_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  body VARCHAR(4000) NOT NULL,
  link_url VARCHAR(500),
  created_by_admin_id BIGINT,
  sent_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(created_by_admin_id) REFERENCES users(id)
);

-- read_atは開封率・配信後何時間で読まれたか等を後から分析できるよう、booleanではなく
-- 実際の既読日時を保存する(NULL=未読)。(message_id, user_id)にUNIQUE制約を付け、
-- 同一メッセージが同じユーザーへ重複登録されないようにする。
CREATE TABLE admin_message_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  read_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(message_id) REFERENCES admin_messages(id),
  FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT uk_admin_message_recipient UNIQUE(message_id, user_id)
);

-- 未読件数取得(user_id + read_at IS NULLでのCOUNT)とユーザー別一覧のページングを高速化する。
CREATE INDEX idx_admin_message_recipients_user_unread ON admin_message_recipients(user_id, read_at);
CREATE INDEX idx_admin_message_recipients_message ON admin_message_recipients(message_id);
CREATE INDEX idx_admin_messages_sent_at ON admin_messages(sent_at);
