-- ログイン後お知らせ(モーダル表示)。運営メッセージ(admin_messages/admin_message_recipients、
-- 通知一覧に残るBOX型)とは別機能: こちらはログイン後ページ表示時に画面中央モーダルとして
-- 一度だけ見せる想定のため、本体(お知らせ内容・公開期間)と配信対象ごとの表示状態を分離する。
-- created_by_admin_idはNULL許容: 送信した管理者アカウントが退会した場合でも
-- お知らせ本体・他の対象者のレコードは残す(created_by_admin_idだけNULLにする)ため。
CREATE TABLE admin_announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  body VARCHAR(4000) NOT NULL,
  link_url VARCHAR(500),
  created_by_admin_id BIGINT,
  starts_at TIMESTAMP NOT NULL,
  ends_at TIMESTAMP,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  priority INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(created_by_admin_id) REFERENCES users(id)
);

-- first_displayed_at/last_displayed_at/display_countは、モーダルを実際にユーザーへ
-- 返した時点でサーバー側が記録する(将来の未読率・開封率・表示回数分析のため)。
-- dismissed_permanently_atは「次回以降このお知らせを表示しない」を選んだ日時
-- (お知らせ単位。ユーザーの全体設定ではない)。(announcement_id, user_id)にUNIQUE制約を付け、
-- 同一お知らせが同じユーザーへ重複登録されないようにする。
CREATE TABLE admin_announcement_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  first_displayed_at TIMESTAMP,
  last_displayed_at TIMESTAMP,
  display_count INT NOT NULL DEFAULT 0,
  dismissed_permanently_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(announcement_id) REFERENCES admin_announcements(id),
  FOREIGN KEY(user_id) REFERENCES users(id),
  CONSTRAINT uk_admin_announcement_recipient UNIQUE(announcement_id, user_id)
);

-- ログイン後の表示対象検索(user_id + dismissed_permanently_at IS NULLでの絞り込み)を高速化する。
CREATE INDEX idx_admin_announcement_recipients_user_pending ON admin_announcement_recipients(user_id, dismissed_permanently_at);
-- 配信履歴(配信人数・表示済み人数・永久非表示人数の集計)を高速化する。
CREATE INDEX idx_admin_announcement_recipients_announcement ON admin_announcement_recipients(announcement_id);
-- 管理画面の一覧・表示対象抽出(published + starts_at)を高速化する。
CREATE INDEX idx_admin_announcements_starts_at ON admin_announcements(starts_at);
