-- Google認証での新規ユーザー作成時のみtrueになるフラグ(User.forGoogleSignup参照)。
-- 既存ユーザー(Google経由・通常登録どちらも)はDEFAULT FALSEにより自動的にfalseとなり、
-- 「新規Google登録ユーザーだけ」に規約同意を強制する判定に使う
-- (termsAgreedAtがNULLというだけの理由で既存ユーザー全員へ強制しないため)。
ALTER TABLE users ADD COLUMN terms_consent_pending BOOLEAN NOT NULL DEFAULT FALSE;

-- お問い合わせ。name/email/subject/bodyは送信当時の内容としてそのまま保持し、
-- userは事後の運営メッセージ連携のためログイン中の送信者がいれば紐付ける(未ログインならNULL)。
-- related_post_idは「不適切な投稿の報告」等で対象の体験談を紐付ける場合のみ設定する(任意)。
CREATE TABLE contact_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  category VARCHAR(20) NOT NULL,
  name VARCHAR(100),
  email VARCHAR(254) NOT NULL,
  subject VARCHAR(100) NOT NULL,
  body VARCHAR(3000) NOT NULL,
  related_post_id BIGINT,
  status VARCHAR(20) NOT NULL,
  admin_memo VARCHAR(2000),
  resolved_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(related_post_id) REFERENCES experience_posts(id)
);

-- 管理画面の一覧(ステータス絞り込み・新着順)と未対応件数バッジを高速化する。
CREATE INDEX idx_contact_inquiries_status ON contact_inquiries(status);
CREATE INDEX idx_contact_inquiries_created_at ON contact_inquiries(created_at);
