-- 投稿貢献度に応じたプレミアム特典還元機能。
-- 「特典マスタ(benefit_definitions)」「投稿数と特典の対応(post_reward_milestones)」
-- 「ユーザーが実際に保有する特典(user_benefits)」「Stripe Webhookの二重処理防止
-- (stripe_webhook_events)」の4テーブルと、users側のStripe Customer/Subscription ID
-- カラムを追加する。将来キャンペーン付与等の別sourceにも対応できるよう、user_benefitsの
-- source_type/source_reference_id/source_descriptionは投稿報酬専用にせず汎用的にしている。

-- Stripe側でユーザーを一意に特定するためのCustomer/Subscription ID。
-- 決済を一度もしていない既存ユーザーは全員NULLから始まる。
ALTER TABLE users ADD COLUMN stripe_customer_id VARCHAR(255);
ALTER TABLE users ADD COLUMN stripe_subscription_id VARCHAR(255);
CREATE UNIQUE INDEX uk_users_stripe_customer_id ON users(stripe_customer_id);
CREATE UNIQUE INDEX uk_users_stripe_subscription_id ON users(stripe_subscription_id);

-- 特典マスタ。Stripe Couponの実IDは環境ごとに異なる(テスト/本番)ため、実IDそのものではなく
-- stripe_coupon_key(application.yml/環境変数で実IDへ解決するための論理キー)を保持する。
-- expires_days: この日数だけ有効なポイント特典を将来作れるようにするための列。今回の
-- 投稿報酬は「原則有効期限なし」のためNULL(=無期限)で運用する。
CREATE TABLE benefit_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  benefit_type VARCHAR(30) NOT NULL,
  discount_percent INT,
  free_months INT,
  description VARCHAR(500),
  expires_days INT,
  stripe_coupon_key VARCHAR(100) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_benefit_definitions_code UNIQUE(code)
);

-- 投稿数と特典の対応(DB駆動、Javaコードへのハードコード禁止)。repeat_intervalが設定されている
-- 行は、required_post_countを起点として以後この間隔で無限に繰り返し付与対象になる
-- (例: required_post_count=10, repeat_interval=10 → 10,20,30,40...を全て対象とみなす)。
-- NULLの行は1回きり(required_post_countちょうどの時のみ)。
CREATE TABLE post_reward_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  required_post_count INT NOT NULL,
  benefit_definition_id BIGINT NOT NULL,
  repeat_interval INT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(benefit_definition_id) REFERENCES benefit_definitions(id),
  CONSTRAINT uk_post_reward_milestones_required_count UNIQUE(required_post_count)
);

-- ユーザーが実際に保有する特典。benefit_name_snapshot以下の*_snapshot列は、付与した瞬間の
-- benefit_definitionsの内容をコピーして保持するためのもの(付与後にマスタ設定(割引率等)を
-- 変更しても、既に付与済みの特典の表示内容が勝手に変わらないようにするため)。
-- reward_grant_keyは同一達成に対する二重付与を防ぐための一意キー(例: POST_COUNT:{userId}:5)。
-- 投稿報酬以外のsource(将来の管理者手動付与・キャンペーン等)はこのキーを使わない場合がある
-- ためNULL許容とし、UNIQUE制約はNULLを複数許容するDBの標準動作にそのまま乗せる。
CREATE TABLE user_benefits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  benefit_definition_id BIGINT NOT NULL,
  source_type VARCHAR(30) NOT NULL,
  source_reference_id BIGINT,
  source_description VARCHAR(300),
  reward_grant_key VARCHAR(150),
  status VARCHAR(20) NOT NULL,
  benefit_name_snapshot VARCHAR(100) NOT NULL,
  benefit_type_snapshot VARCHAR(30) NOT NULL,
  discount_percent_snapshot INT,
  free_months_snapshot INT,
  stripe_coupon_key_snapshot VARCHAR(100) NOT NULL,
  granted_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP,
  reserved_at TIMESTAMP,
  applied_at TIMESTAMP,
  used_at TIMESTAMP,
  revoked_at TIMESTAMP,
  stripe_checkout_session_id VARCHAR(255),
  stripe_subscription_id VARCHAR(255),
  stripe_invoice_id VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(benefit_definition_id) REFERENCES benefit_definitions(id),
  CONSTRAINT uk_user_benefits_reward_grant_key UNIQUE(reward_grant_key)
);
CREATE INDEX idx_user_benefits_user_status ON user_benefits(user_id, status);
CREATE INDEX idx_user_benefits_checkout_session ON user_benefits(stripe_checkout_session_id);

-- Stripe Webhookの同一イベント再送による二重処理を防ぐ。処理開始前にstripe_event_idの
-- INSERTを試み、UNIQUE制約違反になれば既に処理済みとして即座に200を返す(処理本体は行わない)。
CREATE TABLE stripe_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id VARCHAR(255) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  processed_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_stripe_webhook_events_event_id UNIQUE(stripe_event_id)
);

-- 投稿報酬の初期設定(要件どおり)。stripe_coupon_keyはapplication.yml/環境変数側で
-- テスト/本番それぞれの実Coupon IDへ解決する(実IDはここへ書かない)。
INSERT INTO benefit_definitions(code, name, benefit_type, discount_percent, free_months, description, stripe_coupon_key, active, created_at, updated_at)
SELECT 'DISCOUNT_20', 'プレミアム20%OFF', 'PREMIUM_DISCOUNT', 20, NULL, '次回請求が20%OFFになります', 'DISCOUNT_20', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM benefit_definitions WHERE code = 'DISCOUNT_20');

INSERT INTO benefit_definitions(code, name, benefit_type, discount_percent, free_months, description, stripe_coupon_key, active, created_at, updated_at)
SELECT 'DISCOUNT_30', 'プレミアム30%OFF', 'PREMIUM_DISCOUNT', 30, NULL, '次回請求が30%OFFになります', 'DISCOUNT_30', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM benefit_definitions WHERE code = 'DISCOUNT_30');

INSERT INTO benefit_definitions(code, name, benefit_type, discount_percent, free_months, description, stripe_coupon_key, active, created_at, updated_at)
SELECT 'DISCOUNT_50', 'プレミアム50%OFF', 'PREMIUM_DISCOUNT', 50, NULL, '次回請求が50%OFFになります', 'DISCOUNT_50', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM benefit_definitions WHERE code = 'DISCOUNT_50');

INSERT INTO benefit_definitions(code, name, benefit_type, discount_percent, free_months, description, stripe_coupon_key, active, created_at, updated_at)
SELECT 'FREE_MONTH', 'プレミアム1か月無料', 'PREMIUM_FREE_MONTH', NULL, 1, '次回請求が無料になります', 'FREE_MONTH', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM benefit_definitions WHERE code = 'FREE_MONTH');

-- 投稿数マイルストーン(要件どおり: 1件→20%OFF, 3件→30%OFF, 5件→50%OFF,
-- 10件以降10件ごと→1か月無料を繰り返し付与)。
INSERT INTO post_reward_milestones(required_post_count, benefit_definition_id, repeat_interval, active, display_order, created_at, updated_at)
SELECT 1, (SELECT id FROM benefit_definitions WHERE code = 'DISCOUNT_20'), NULL, TRUE, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM post_reward_milestones WHERE required_post_count = 1);

INSERT INTO post_reward_milestones(required_post_count, benefit_definition_id, repeat_interval, active, display_order, created_at, updated_at)
SELECT 3, (SELECT id FROM benefit_definitions WHERE code = 'DISCOUNT_30'), NULL, TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM post_reward_milestones WHERE required_post_count = 3);

INSERT INTO post_reward_milestones(required_post_count, benefit_definition_id, repeat_interval, active, display_order, created_at, updated_at)
SELECT 5, (SELECT id FROM benefit_definitions WHERE code = 'DISCOUNT_50'), NULL, TRUE, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM post_reward_milestones WHERE required_post_count = 5);

INSERT INTO post_reward_milestones(required_post_count, benefit_definition_id, repeat_interval, active, display_order, created_at, updated_at)
SELECT 10, (SELECT id FROM benefit_definitions WHERE code = 'FREE_MONTH'), 10, TRUE, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM post_reward_milestones WHERE required_post_count = 10);
